baseurl: '/'
exclude: ['README.md']
permalink: pretty
title: 'Sanjay Anand's Professional Page for Collaborators and Hiring Employers'

google_analytics_id: null
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/logo-mobile.svg"
  desktop: "images/logo/logo.svg"
  desktop_height: "36px"
footer:
  copyright_text: 'Sanjay Anand Professional <a class="zerostatic" href="https://www.sanjayanand.pro/copyright_text">www.sanjayanand.pro</a>'

seo:
  meta_og_title: "Sanjay Anand Professional"
  meta_og_type: "website"
  meta_og_url: "https://jekyll-serif-theme.netlify.app"
  meta_og_image: "https://raw.githubusercontent.com/zerostaticthemes/jekyll-serif-theme/master/screenshots/tn.png"
  meta_og_description: "Sanjay Anand Professional page contains his present and past pro bono projects and digital projections"
  meta_twitter_card: "summary"
  meta_twitter_site: "@sanju7"
  meta_twitter_creator: "@sanju7"

collections:
  services:
    output: true
    permalink: /services/:path/
  team:
    output: true
    permalink: /team/:path/

defaults:
  - scope:
      type: services
    values:
      layout: service
      bodyClass: page-services-single
  - scope:
      path: 'images'
    values:
      image: true

sass:
  style: compact # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables
